CREATE DATABASE SQLCOURSE; 

-- Se debe crear primero la base de datos antes de correr los scripts.

-- Tabla REGIONS
CREATE TABLE REGIONS (
    REGION_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    REGION_NAME VARCHAR(25)
);

-- Tabla COUNTRIES
CREATE TABLE COUNTRIES (
    COUNTRY_ID CHAR(2) PRIMARY KEY,
    COUNTRY_NAME VARCHAR(40),
    REGION_ID INTEGER NOT NULL,
    FOREIGN KEY (REGION_ID) REFERENCES REGIONS (REGION_ID) ON DELETE CASCADE
);

-- Tabla LOCATIONS
CREATE TABLE LOCATIONS (
    LOCATION_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    STREET_ADDRESS VARCHAR(40),
    POSTAL_CODE VARCHAR(12),
    CITY VARCHAR(30) NOT NULL,
    STATE_PROVINCE VARCHAR(25),
    COUNTRY_ID CHAR(2) NOT NULL,
    FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES (COUNTRY_ID) ON DELETE CASCADE
);

-- Tabla DEPARTMENTS
CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(30) NOT NULL,
    LOCATION_ID INTEGER,
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS (LOCATION_ID) ON DELETE CASCADE
);

-- Tabla JOBS
CREATE TABLE JOBS (
    JOB_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JOB_TITLE VARCHAR(35) NOT NULL,
    MIN_SALARY DECIMAL(8,2),
    MAX_SALARY DECIMAL(8,2)
);

-- Tabla EMPLOYEES
CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(25) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE_NUMBER VARCHAR(20),
    HIRE_DATE DATE NOT NULL,
    JOB_ID INTEGER NOT NULL,
    SALARY DECIMAL(8,2) NOT NULL,
    MANAGER_ID INTEGER,
    DEPARTMENT_ID INTEGER,
    FOREIGN KEY (JOB_ID) REFERENCES JOBS (JOB_ID) ON DELETE CASCADE,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS (DEPARTMENT_ID) ON DELETE CASCADE,
    FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID) ON DELETE CASCADE
);

-- Tabla DEPENDENTS
CREATE TABLE DEPENDENTS (
    DEPENDENT_ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    RELATIONSHIP VARCHAR(25) NOT NULL,
    EMPLOYEE_ID INTEGER NOT NULL,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID) ON DELETE CASCADE
);
